### ISSUE TITLE
Implementación en VFP

### ISSUE THREAD

**Issue by pibarra857** [jca-ec/smswhatsapp#1]
En la demo version VFP falta el archivo vfpstretch.prg

**Comment by jca-ec** [comment]
Hola, por favor revísalo.

Te recomiendo que nos contactes al +593 984 958 499.

 

Por correo electrónico pocas veces estamos disponibles, por WhatsApp es casi inmediato.

 

Saludos coordiales

 

 

De: pibarra857 ***@***.***> 
Enviado el: lunes, 8 de abril de 2024 14:28
Para: jca-ec/smswhatsapp ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [jca-ec/smswhatsapp] Implementacion en VFP (Issue #1)

 

En la demo version VFP falta el archivo vfpstretch.prg
